### ISSUE TITLE
font is more smaller

### ISSUE THREAD

**Issue by morning-start** [microsoft/vscode-edge-devtools#1323]
![image](https://user-images.githubusercontent.com/76601464/211011148-52df2e7e-bf67-4436-a70e-3a20acd43707.png)
![image](https://user-images.githubusercontent.com/76601464/211011228-32f58c58-6a07-4870-83ac-47302c6dcffe.png)

the font size is smaller then brower

**Comment by morning-start** [comment]
there is code

![image](https://user-images.githubusercontent.com/76601464/211011407-276fe90b-0472-4a68-a906-8d79de17d3d5.png)

```html
<div class="icon email">
    <p class="tip-num">20</p>
</div>
```

```css
.icon {
    width: 25px;
    height: 25px;
    margin: 0 10px;
    background-size: 100% 100%;
    position: relative;
}
.email {
    background-image: url('../icons/email-fill.png');
}
.tip-num {
    position: absolute;
    top: -10px;
    right: -2px;
    height: 15px;
    width: 15px;
    text-align: center;
    font-size: 6px;
    background-color: red;
    color: white;
    border-radius: 50%;
}
```
